version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: thinkify-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: thinkify
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - thinkify-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: thinkify-server
    restart: unless-stopped
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://admin:password123@mongodb:27017/
      - DATABASE_NAME=thinkify
      - BCRYPT_GEN_SALT_NUMBER=10
      - JWT_SECRET_KEY=abcdefghijklmnopqrstuvwxyz
      - COOKIE_EXPIRES=5d
      - COOKIE_KEY=thinkify
      - UPLOAD_DIRECTORY=uploads
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - server_uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - thinkify-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: thinkify-client
    restart: unless-stopped
    environment:
      - VITE_SERVER_ENDPOINT=http://localhost:3000/api
      - VITE_TOKEN_KEY=thinkify
      - VITE_USER_ROLE=role
      - VITE_COOKIE_EXPIRES=1
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - thinkify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mongodb_data:
    driver: local
  server_uploads:
    driver: local

networks:
  thinkify-network:
    driver: bridge
